name: Deploy Kdoc

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  artifact_path: app/build/dokka/html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build Kdoc
      run: |
        chmod +x gradlew
        ./gradlew dokkaHtml
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with: 
        path: ${{ env.artifact_path }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
